### ISSUE TITLE
Checklist about Beetle releases

### ISSUE THREAD

**Issue by yunkon-kim** [cloud-barista/cm-beetle#141]
@yunkon-kim @seokho-son @sykim-etri (cc. @ish-hcc @dev4unet)

안녕하세요.

📅 Beetle v0.2.x릴리스 일정이 ~11/15(금)~ -> 11/18(월)로 조정되었습니다. 

앞서 릴리스된 CM-Honeybee, CM-Damselfly (+ cm-model), CB-Tumblebug을 활용하여, 
AWS, Azure, NCP를 대상으로 목표 클라우드 인프라 추천 및 마이그레이션 기능의 정상 동작 여부를 확인 후 릴리스할 계획을 가지고 있습니다.

🙋 먼저, 관련하여 이슈가 있으신 경우 댓글로 남겨주시기 바랍니다.

☑️ 아래 사항들에 대해 추진을 부탁드리며, 완료된 항목들은 Checked 처리하여 주십시오.
* [x] Beetle 개발 및 테스트
* [x] Beetle 관련 서브시스템과 통합 테스트 ([Sequence Diagram](https://github.com/cloud-barista/cloud-migrator/blob/main/docs/sequence-diagrams-for-user-scenarios.md) 참고 및 개선)
* [x] Beetle 실행 지원
* [x] Beetle 문서화
* [x] Beetle 릴리스
각 항목별 자세한 사항은 아래 링크의 "저장소별 추진사항"을 참고하시면 될 것 같습니다.
Ref: https://github.com/cloud-barista/cloud-migrator/issues/11

아울러, 릴리스 이후 상위/타 서브시스템에서의 통합 및 테스트가 진행됩니다. 이 부분에 대해 미리 협조를 부탁드립니다.

(참고)
이번 Cloud-Migrator v0.3.0 통합 및 릴리스는 두 가지 측면에서 진행됩니다.

* 컴퓨팅 인프라 마이그레이션: Cloud-Migration portal에서 3종 클라우드로, 3종 자원에 대해 마이그레이션을 수행할 수 있어야 함
* SW 마이그레이션: 기능 개발, 테스트 및 통합 추진 (portal 통합 대상 X)

**Comment by yunkon-kim** [comment]
Note 

통합 및 테스트 진행 환경:
* cm-model v0.0.3 (Damselfly v0.2.1)
* Honeybee v0.2.10
* Tumblebug v0.10.0 (Spider v0.10.0, CB-MapUI v0.10.0)

통합 및 테스트 시나리오:
1. 온프레미스 인프라 모델을 활용 > AWS에 맞는 최적 클라우드 인프라를 추천 > 마이그레이션 수행 
2. 온프레미스 인프라 모델을 활용 > Azure에 맞는 최적 클라우드 인프라를 추천 > 마이그레이션 수행 
3. 온프레미스 인프라 모델을 활용 > NCP에 맞는 최적 클라우드 인프라를 추천 > 마이그레이션 수행

**Comment by yunkon-kim** [comment]
@ish-hcc @dev4unet @hippo-an 

Cicada, Ant, Butterfly 메인테이너께 양해를 구합니다. 

갑작스런 이슈로 인해 Beetle 릴리스 일정 조정이 필요한 상황입니다. 
* https://github.com/cloud-barista/cb-tumblebug/issues/1925 

11/18(월)까지 릴리스 찍을 수 있을 것으로 예상됩니다. Beetle API 또한 변경 없이 제공해 드리도록 하겠습니다.

**Comment by yunkon-kim** [comment]
@ish-hcc @dev4unet @hippo-an

Beetle v0.2.4 릴리스를 안내 드립니다. 
연관된 서브시스템 및 버전, API를 통한 테스트 시나리오 등과 관련한 자세한 사항은 아래 링크를 참고하시기 바라며, 궁금한 사항이 있으시면 댓글 남겨주십시오.
* https://github.com/cloud-barista/cm-beetle/releases/tag/v0.2.4
